// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7lk0saTwg_dHO50vpLdgGhZQ7NwYD1y8',
    appId: '1:344683661506:web:70a2fd30e38f3c0e7e935b',
    messagingSenderId: '344683661506',
    projectId: 'taskmanagement-697da',
    authDomain: 'taskmanagement-697da.firebaseapp.com',
    storageBucket: 'taskmanagement-697da.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmZ5u07KzPpIi-LQCNfs-_VLtGL9RJBRc',
    appId: '1:344683661506:android:9a8460e63b08afb27e935b',
    messagingSenderId: '344683661506',
    projectId: 'taskmanagement-697da',
    storageBucket: 'taskmanagement-697da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc1qghKiNRc6_O3zUWbxVq3MYg7vBRG3o',
    appId: '1:344683661506:ios:9f53bc7fb35707f07e935b',
    messagingSenderId: '344683661506',
    projectId: 'taskmanagement-697da',
    storageBucket: 'taskmanagement-697da.firebasestorage.app',
    iosBundleId: 'com.example.taskManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc1qghKiNRc6_O3zUWbxVq3MYg7vBRG3o',
    appId: '1:344683661506:ios:9f53bc7fb35707f07e935b',
    messagingSenderId: '344683661506',
    projectId: 'taskmanagement-697da',
    storageBucket: 'taskmanagement-697da.firebasestorage.app',
    iosBundleId: 'com.example.taskManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7lk0saTwg_dHO50vpLdgGhZQ7NwYD1y8',
    appId: '1:344683661506:web:9c1703b9c2d337937e935b',
    messagingSenderId: '344683661506',
    projectId: 'taskmanagement-697da',
    authDomain: 'taskmanagement-697da.firebaseapp.com',
    storageBucket: 'taskmanagement-697da.firebasestorage.app',
  );
}
